<!-- Synced from `/Users/hu_zhehao/Desktop/zzzhehao/note/evolution/MSc EvoSys Course/02 Phylogeny Fundamentals.md` -->

# Phylogeny Fundamentals

Fundamentals for understanding phylogeny.

## Character States

- **Apomorphy** = a derived trait, shared by two or more taxa from a common ancestor is synapomorphy, unique to a given taxa is autapomorphy
- **Synapomorphy** = character present in an ancestral species and shared exclusively by its evolutionary descendants
- **Autapomorphy** = apomorphy unique to a given taxa or group, not parsimony informative
- **Symplesiomorphy / Plesiomorphy** = ancestral state shared by all the membre of a clade, which can not distinguish the clade from other clades

… these are the state of a character, based on the objective observations and data.

> Symplesiomorphy is synapomorphy at a less inclusive level, which is not useful for phylogenetic classification ([Patterson, 1982](https://onlinelibrary.wiley.com/doi/full/10.1111/j.1096-0031.2012.00431.x#b17); [de Pinna, 1991](https://onlinelibrary.wiley.com/doi/full/10.1111/j.1096-0031.2012.00431.x#b18); [Schuh and Brower, 2009](https://onlinelibrary.wiley.com/doi/full/10.1111/j.1096-0031.2012.00431.x#b21)).
>
>- [Assis, 2013]([https://doi.org/10.1111/j.1096-0031.2012.00431.x](https://doi.org/10.1111/j.1096-0031.2012.00431.x))

## Convergent Evolution

**Convergent evolution** = independent evolution of similar features, creates analogous

- Morphologcial convergence > e.g., similar body form of succulent plant (_Euphorbia_ and _Astrophytum_)

- **Homology, Homoplasy**: is a hypothesis, which describe how a character has evolved.

> As aptly remarked by [Müller (2003, p. 54](https://onlinelibrary.wiley.com/doi/full/10.1111/j.1096-0031.2012.00431.x#b12):
> 
> \[…\] its \[element\] absence, may serve as a shared, derived (taxonomical) character – a synapomorphy. Moreover, a taxonomical character is not necessarily the same as a morphological character. **All homologues are synapomorphics, but not vice-versa.** Absence of an anatomical element, for instance, can be a taxonomical synapomorphy but not a homology, because homologues are positive anatomical parts. **Hence _synapomorphy_ and _homology_ should not be considered as synonymous.**
>
>- [Assis, 2013]([https://doi.org/10.1111/j.1096-0031.2012.00431.x](https://doi.org/10.1111/j.1096-0031.2012.00431.x))

- **Orthology**: originated from speciation

- **Paralogy**: originated from gene duplication

- **Xenology**: originated from horizontal gene transfer

## **Paraphyly vs. Polyphyly**

> However, paraphyletic and polyphyletic groups are not realistically acceptable ([Hennig, 1965, 1966](https://onlinelibrary.wiley.com/doi/10.1111/j.1096-0031.2012.00431.x#b7%20#b8)), even though these groups are defined by symplesiomorphies and homoplasies, respectively. Ironically, there exists a clear distinction between character evolution and group classification.
>
>- [Assis, 2013]([https://doi.org/10.1111/j.1096-0031.2012.00431.x](https://doi.org/10.1111/j.1096-0031.2012.00431.x))

> Symplesiomorphy entails paraphyly, so that _some_, _not all_, descendant species inherited a particular (plesiomorphic) condition from a common ancestor of them. Homoplasy entails polyphyly—i.e. independent origin (non-homology) of a similar condition in two or more groups—but it is synapomorphy at a more restricted phylogenetic level (compare [Hall, 2007](https://onlinelibrary.wiley.com/doi/full/10.1111/j.1096-0031.2012.00431.x#b6); [Scotland, 2011](https://onlinelibrary.wiley.com/doi/full/10.1111/j.1096-0031.2012.00431.x#b22); [Nixon and Carpenter, 2012](https://onlinelibrary.wiley.com/doi/full/10.1111/j.1096-0031.2012.00431.x#b15)).
>
>- [Assis, 2013]([https://doi.org/10.1111/j.1096-0031.2012.00431.x](https://doi.org/10.1111/j.1096-0031.2012.00431.x))
