<!-- Synced from `/Users/hu_zhehao/Desktop/zzzhehao/note/evolution/MSc EvoSys Course/06 Phylogenetic Marker.md` -->

# Phylogenetic Marker

## Nuclear Single-Copy-Marker

Fine, but …

- Small amount is not easy to amplify
- Problem of introns
- diploid inheritance: cloning might be necessary
- recombination

## Ribosomal DNA

- abundant
- highly conserved, universal primer is possible
- alighment is much more difficult since no reading frame is applied
- 18S is more conserved than 28S

## Mitochondrial DNA

Ring DNA

- 15-20 kb, 22 tRNAs, 2 rRNAs, 13 proteins, control region
- abundant (5-10 DNA in one Mitochondrium, ca. 1000 Mitochondria/cell
- almost homoplastic (maternal inheritance as bottle neck)
- no intron
- rapid lineage sorting
- no recombination
- no pseudogene (but possible in nuclear mitochondrial DNA segment)
- no repare system, thus higher substitution rate

## DNA Barcoding, DNA Fingerprinting (profiling)

DNA Marker, e.g., COI, etc.

### Microsatellite

- 10-100 repeats of a 1-6 bp DNA fragment

### AFLP (Amplified fragment length polymorphism)

- selective amplification of a subset of digested DNA fragment to generate and compare unique fingerprints for genome of interest
- do not require prior information regarding the targeted genome
- for assessing intragenetic, population-level phylogenies and biogeographic patterns

### RAD (Restriction site associated DNA sequencing), ddRAD

- SNPs: single nucleotide polymorphisms
- Codominant Marker