<!-- Synced from `/Users/hu_zhehao/Desktop/zzzhehao/note/evolution/MSc EvoSys Course/10 Molecular Clocks.md` -->

# Molecular Clocks

Methods based on the hypothesis that DNA evolves at a constant rate over time …

- if evolutionary rates are “clock-like”, mutation rates could be used to estimate divergence times, calibrating one part of the tree with a know date allows estimation of other parts of the tree based on the “clock-like” expectation

Calibration of the age can be based on …

- Fossils (oldest fossile for a clade to constrain the minimum age of a node)
- Geological vicariance events (e.g., the closure of Panamanian isthmus, using sister species on either side of that barrier, we can constrain the node to the approximate timing of their separation)

Node calibration can be implemented by setting Bayesian priors on the ages of nodes.

## Diversification Rate

- **Speciation rate ($\lambda$)** - the rate at which new species form
- **Extinction rate ($\mu$)** - the rate at which species disappear
- **Net diversification** - speciation - extinction
- **Lineage turnover** - extinction / speciation

## Clock Model

### Pure-birth model

Assumes no extinction, diversification rate increases

### Birth-death model

Assumes ...

- Speciation and extinction occur at random
- each lineage has an equal and constant rate of speciation and extinction
- even phylogenies with only extant species leave cluse about extinction, which is more likely to have occurred in older lineages, leading to “pull of the present”