<!-- Synced from `/Users/hu_zhehao/Desktop/zzzhehao/note/evolution/MSc EvoSys Course/99 Concept Checklist.md` -->

# Concept Checklist

- Akaike Information Criterion
- Binary / Multistate
- Bifurcation
- Bremer Decay Index
- Brownian Motion
- Character Transformation
- Characters and Character states
- Coalescene
- Consensus trees
- Continuous / Discrete
- Diversification rate
- DNA fingerprinting
- Evoluationary / statistical correlation
- Genetic distance
- Genotype / Phenotype
- Homology, Homoplasy
- Hybridization
- Informative / Uninformative sites
- Indel
- Linnean classification
- Macroevolution
- Markov chain Monte Carlo (MCMC)
- Models of character evolution
- Models of sequence alignment
- Models of sequence evolution
- Molecular clock
- Molecular data partitions
- Monophyly, Polyphyly, Paraphyly
- Morphological convergence
- Multiple sequence alignment (MSA)
- Next-generation sequencing
- Orthology, Paralogy
- Plesiomorphy, Symplesiomorphy
- Population genetics
- Phylogenetic Independent Contrast
- Phylogenetics / Phylogenomics
- Polytomy
- Quantitative / Qualitative
- Restriction sites
- Sanger sequencing
- Saturation
- Species delimination
- Speciation rate / Extinction rate
- Substitution
- Supertree / Supermatrix
- Tree congruence / incongruence
- Tree length
- Tree score
- Tree space
- Tree-thinking
- Variant / Invariant sites