<!-- Synced from `/Users/hu_zhehao/Desktop/zzzhehao/note/ecology/Isolation By Distance (IBD).md` -->

## Signpost
- [The restricted gene flow caused by the distance between populations can result in isolation by distance (IBD), a population structure model described in Sewall Wright’s seminal works (Wright, 1940, 1943). (perez2018, p.1884)](../../../90-99%20Resources/90%20References/80.02%20Zotero%20File%20Storage/perez2018.pdf#page=2&selection=20,0,24,6&color=note%20/%20signpost) 
- [Isolation by distance is predicted to be a ubiquitous process, as limited dispersal is believed to affect most species (Meirmans, 2012; Rousset, 1997) (perez2018, p.1885)](../../../90-99%20Resources/90%20References/80.02%20Zotero%20File%20Storage/perez2018.pdf#page=3&selection=131,0,156,14&color=note%20/%20signpost)
- [We believe this proportion can be underestimated, as IBD tests can be nonsignificant even when IBD is present. Indeed, studies sampling from pre-defined populations showed a lower (Wilcoxon signed-rank test p = 0.0001) proportion of IBD detection (53.61% of the articles that tested for IBD detected its presence) than collecting individuals in a continuous landscape (85.71% of IBD detection). This difference can be related to the lack of statistical power in spatial correlation analyses with a small number of pairwise comparisons (Jenkins et al., 2010; Pelletier & Carstens, 2018), which is often the case in studies sampling defined populations.  (perez2018, p.1885)](../../../90-99%20Resources/90%20References/80.02%20Zotero%20File%20Storage/perez2018.pdf#page=3&selection=167,0,258,19&color=note%20/%20signpost)